### PR TITLE
Add Partis.si

### PR DESCRIPTION
**Pull request by aaaxx**
Slovenian private tracker with general content, pretty popular in the Balkan countries.

### CODE REVIEW

**Comment by buzz** [comment]
Can you contribute a results matcher string for this site?
Logged in matcher I already have: `Za nadaljevanje vpišite vaše uporabniško ime in geslo`. :)

**Comment by aaaxx** [comment]
It's one of those dynamic cases, so it doesn't work. Is there any way to get around that?

**Comment by buzz** [comment]
It depends on the website. Some sites have APIs that they use to retrieve the results. This API could be used (see #9).

**Comment by aaaxx** [comment]
Yeah, I've checked the forum and wiki and there's no mention of APIs, so it's probably best to just merge as is.

**Pull request merged**
